export const ESTILISTAS = [
    { id: 1, nombre: "Noelia", especialidad: "Cabello", color: "#3B82F6" },
    { id: 2, nombre: "Kathy", especialidad: "Tratamientos corporales", color: "#A855F7" },
    { id: 3, nombre: "Yazmine", especialidad: "Uñas", color: "#10B981" },
    { id: 4, nombre: "Kati", especialidad: "Todo terreno", color: "#9F0BF5" },
    { id: 5, nombre: "Sharom", especialidad: "Cara", color: "#8F0A3D" },
    { id: 6, nombre: "Jimena", especialidad: "Uñas", color: "#F09813" },
];

export const TRATAMIENTOS = [
    { id: 1, nombre: "Botox Capilar", duracion: 90, categoria: "Cabello" },
    { id: 2, nombre: "Tinte + botox", duracion: 120, categoria: "Cabello" },
    { id: 3, nombre: "Tinte + tratamiento", duracion: 90, categoria: "Cabello" },
    { id: 4, nombre: "Tinte", duracion: 70, categoria: "Cabello" },
    { id: 5, nombre: "Tratamiento", duracion: 60, categoria: "Cabello" },
    { id: 6, nombre: "Corte de puntas", duracion: 20, categoria: "Cabello" },
    { id: 7, nombre: "Corte forma", duracion: 30, categoria: "Cabello" },
    { id: 8, nombre: "Corte + lavado", duracion: 40, categoria: "Cabello" },
    { id: 9, nombre: "Corte + lavado + tratamiento", duracion: 70, categoria: "Cabello" },
    { id: 10, nombre: "Corte + lavado + planchado", duracion: 70, categoria: "Cabello" },
    { id: 11, nombre: "Mechas bayalage", duracion: 240, categoria: "Cabello" },
    { id: 12, nombre: "Mechas general", duracion: 300, categoria: "Cabello" },
    { id: 13, nombre: "Mechas creativas", duracion: 300, categoria: "Cabello" },
    { id: 14, nombre: "Alisado organico", duracion: 120, categoria: "Cabello" },
    { id: 15, nombre: "Alisado japones", duracion: 240, categoria: "Cabello" },
    { id: 16, nombre: "Alisado dual", duracion: 240, categoria: "Cabello" },
    { id: 17, nombre: "Alisado brasilero", duracion: 90, categoria: "Cabello" },
    { id: 18, nombre: "Lavado + planchado", duracion: 90, categoria: "Cabello" },
    { id: 19, nombre: "Pintado Gel", duracion: 30, categoria: "Uñas" },
    { id: 20, nombre: "Pintado Tradicional", duracion: 20, categoria: "Uñas" },
    { id: 21, nombre: "Reforzamiento Gum Gel", duracion: 90, categoria: "Uñas" },
    { id: 22, nombre: "Uñas Acrílicas", duracion: 120, categoria: "Uñas" },
    { id: 23, nombre: "Pedicure Gel", duracion: 90, categoria: "Uñas" },
    { id: 24, nombre: "Pedicure Tradicional", duracion: 40, categoria: "Uñas" },
    { id: 25, nombre: "Uñas Rubber", duracion: 90, categoria: "Uñas" },
    { id: 26, nombre: "Gum Gel Extension", duracion: 120, categoria: "Uñas" },
    { id: 27, nombre: "Extension de pestañas", duracion: 120, categoria: "Cara" },
    { id: 28, nombre: "Retiro de pestañas", duracion: 20, categoria: "Cara" },
    { id: 29, nombre: "Lifting", duracion: 60, categoria: "Cara" },
    { id: 30, nombre: "Laminado", duracion: 40, categoria: "Cara" },
    { id: 31, nombre: "Henna", duracion: 40, categoria: "Cara" },
    { id: 32, nombre: "Micropigmentacion", duracion: 180, categoria: "Cara" },
    { id: 33, nombre: "Botox", duracion: 40, categoria: "Cara" },
    { id: 34, nombre: "Depilacion Cejas Cera", duracion: 30, categoria: "Cara" },
    { id: 35, nombre: "Depilacion Cejas Hilo", duracion: 20, categoria: "Cara" },
    { id: 36, nombre: "Depilacion Bozo Cera", duracion: 30, categoria: "Cara" },
    { id: 37, nombre: "Depilacion Bozo Hilo", duracion: 20, categoria: "Cara" },
    { id: 38, nombre: "Depilacion Total Cara", duracion: 60, categoria: "Cara" },
    { id: 39, nombre: "Facial", duracion: 60, categoria: "Cara" },
    { id: 40, nombre: "Hidralips", duracion: 60, categoria: "Cara" },
    { id: 41, nombre: "Microblading", duracion: 180, categoria: "Cara" },
    { id: 42, nombre: "Peeling", duracion: 60, categoria: "Cara" },
    { id: 43, nombre: "Retoque Labios", duracion: 150, categoria: "Cara" },
    { id: 44, nombre: "Retoque Microblading", duracion: 150, categoria: "Cara" },
    { id: 45, nombre: "Peptonas", duracion: 75, categoria: "Corporal", conteoSesiones: true },
    { id: 46, nombre: "Drenaje Post Operatorio", duracion: 60, categoria: "Corporal" },
    { id: 47, nombre: "Enzimas", duracion: 60, categoria: "Corporal" },
    { id: 48, nombre: "Hidrolipoclasia", duracion: 90, categoria: "Corporal" },
    { id: 49, nombre: "Carboxterapia", duracion: 20, categoria: "Corporal" },
    { id: 50, nombre: "Maderoterapia", duracion: 40, categoria: "Corporal" },
    { id: 51, nombre: "Paquete", duracion: 60, categoria: "Corporal" },
    { id: 52, nombre: "Peinado", duracion: 60, categoria: "Cabello" },
    { id: 53, nombre: "Ampolla", duracion: 60, categoria: "Cabello" },
    { id: 54, nombre: "Maquillaje", duracion: 60, categoria: "Cara" },
    { id: 55, nombre: "Retiro rubber", duracion: 60, categoria: "Uñas" },
    { id: 56, nombre: "Retiro gum gel", duracion: 60, categoria: "Uñas" },
    { id: 57, nombre: "Retiro acrilico", duracion: 60, categoria: "Uñas" },
    { id: 58, nombre: "Depilacion de axilas", duracion: 60, categoria: "Corporal" },
    { id: 59, nombre: "Depilacion de piernas", duracion: 60, categoria: "Corporal" },
];

export const HORARIO_INICIO = 11;
export const HORARIO_FIN = 22;